apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: read-env
  name: go-env-reader
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: go-env-reader
  template:
    metadata:
      labels:
        app: go-env-reader
    spec:
      containers:
      - name: reader
        image: vadimglinsky/env-reader:0.0.1
        env:
          - name: DB_NAME
            value: postgres
          - name: DB_URL
            value: "127.0.0.1"
          - name: DB_PORT
            value: "5432"
        envFrom:
         - secretRef:
             name: some-secret
#          - name: DB_NAME
#            valueFrom:
#              secretKeyRef:
#                name: some-secret
#                key: DB_NAME